name: testing

on:
  release:
    types: [created]

env:
  TEST_STR: base
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: version
        uses: actions/github-script@v4
        with:
          script: |
            const version = context.payload.release.tag_name.substring(1)
            core.exportVariable('VERSION', version)
      - name: Dump env
        run: echo "$ENV"
        shell: bash
        env:
          VERSION2: ${{ toJson(env.version) }}
  other:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Dump env
        run: echo "$ENV"
        shell: bash
        env:
          ENV: ${{ toJson(env) }}
  other2:
    needs: dump
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: echo "$ENV"
        shell: bash
        env:
          ENV: ${{ toJson(env) }}
