name: testing

on:
  schedule:
    - cron: "00 0 * * 0-6"
  push:
    branches:
      - master

env:
  TEST_STR: base
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: version
        uses: actions/github-script@v4
        with:
          script: |
            const version = context
            core.exportVariable('VERISION', version)
      - name: Dump env
        run: echo "$ENV"
        shell: bash
  other:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: echo "$ENV"
        shell: bash
        env:
          JOBS: ${{ toJson(jobs) }}
  other2:
    needs: dump
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: echo "$ENV"
        shell: bash
        env:
          JOBS: ${{ toJson(jobs) }}
