name: testing

on:
  schedule:
    - cron: "00 0 * * 0-6"
  push:
    branches:
      - master

env:
  TEST_STR: base
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: context
        uses: actions/github-script@v4
        with:
          script: |
            const dump = context
            core.exportVariable('DUMP', dump)
      - name: Dump env
        run: echo "$ENV"
        shell: bash
